project_id = "pcwiwtajzqnayfwvqsbh"

[functions.send-prequalification-email]
verify_jwt = false

[functions.generate-lead-email]
verify_jwt = false

[functions.ai-email-chat]
verify_jwt = false

[functions.gmail-api]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.newsletter-webhook]
verify_jwt = false

[functions.newsletter-track]
verify_jwt = false
