#!/bin/bash
# Quick test runner for CommercialLendingX

echo "🧪 CommercialLendingX Test Suite"
echo "=================================="
echo ""
echo "Choose a test to run:"
echo ""
echo "1. Public Pages Test (All public routes)"
echo "   npx playwright test e2e/public-pages.spec.ts --config playwright-simple.config.ts"
echo ""
echo "2. Page Status Check (Homepage diagnostic)"
echo "   npx playwright test e2e/status-check.spec.ts --config playwright-simple.config.ts"
echo ""
echo "3. Auth Diagnostic (Login flow inspection)"
echo "   npx playwright test e2e/auth-diagnostic.spec.ts --config playwright-simple.config.ts"
echo ""
echo "4. Settings Functionality (Full settings page test)"
echo "   npx playwright test e2e/settings-functionality.spec.ts --config playwright-simple.config.ts"
echo ""
echo "5. Run all tests"
echo "   npx playwright test --config playwright-simple.config.ts"
echo ""
echo "6. View test report"
echo "   npx playwright show-report"
echo ""
echo "Note: Dev server must be running on http://localhost:8084"
echo "Start with: npm run dev"
